# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.IntegerField(default=1, verbose_name='minimum search distance')),
                ('max_distance', models.IntegerField(default=10, verbose_name='maximum search distance')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='minimum dating age')),
                ('max_dating_age', models.IntegerField(default=45, verbose_name='maximum dating age')),
                ('dating_sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='F', max_length=8, verbose_name='dating sex')),
                ('vibration', models.BooleanField(default=True, verbose_name='whether vibrate')),
                ('only_matche', models.BooleanField(default=True, verbose_name='only the matched can watch the album')),
                ('auto_play', models.BooleanField(default=True, verbose_name='auto play video')),
                ('location', models.CharField(max_length=32, verbose_name='target city')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('phonenum', models.CharField(max_length=16, unique=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=8)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
